/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var gramatica = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[2,5],$V1=[1,6],$V2=[1,7],$V3=[1,16],$V4=[2,7],$V5=[1,15],$V6=[2,25],$V7=[1,23],$V8=[1,25],$V9=[1,24],$Va=[1,40],$Vb=[1,38],$Vc=[2,15],$Vd=[1,35],$Ve=[1,36],$Vf=[1,37],$Vg=[1,39],$Vh=[1,47],$Vi=[2,29],$Vj=[1,46],$Vk=[1,48],$Vl=[19,25],$Vm=[2,20],$Vn=[1,54],$Vo=[1,53],$Vp=[1,51],$Vq=[1,52];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"inicio":3,"WISON":4,"PREGI":5,"sig":6,"PREGD":7,"LEX":8,"CORCHI":9,"DOS_PUNT":10,"sigLex":11,"CORCHD":12,"SYNTAX":13,"sigSyntax":14,"TERM_PAL":15,"TERMINAL":16,"FLECHA":17,"cads":18,"PUNT_COMA":19,"CADENA":20,"rex":21,"ALFAB":22,"TODOS_NUM":23,"PARI":24,"PARD":25,"ASTER":26,"SUMA":27,"NO_TERM_PAL":28,"NO_TERMINAL":29,"INITIAL_SIM":30,"FLECHADOB":31,"prod":32,"BARRA_VERT":33,"$accept":0,"$end":1},
terminals_: {2:"error",4:"WISON",5:"PREGI",7:"PREGD",8:"LEX",9:"CORCHI",10:"DOS_PUNT",12:"CORCHD",13:"SYNTAX",15:"TERM_PAL",16:"TERMINAL",17:"FLECHA",19:"PUNT_COMA",20:"CADENA",22:"ALFAB",23:"TODOS_NUM",24:"PARI",25:"PARD",26:"ASTER",27:"SUMA",28:"NO_TERM_PAL",29:"NO_TERMINAL",30:"INITIAL_SIM",31:"FLECHADOB",33:"BARRA_VERT"},
productions_: [0,[3,5],[3,1],[6,7],[6,9],[6,0],[11,6],[11,0],[11,2],[11,6],[18,2],[18,2],[18,2],[18,2],[18,4],[18,0],[18,1],[21,1],[21,1],[21,1],[21,0],[21,1],[14,4],[14,4],[14,5],[14,0],[32,2],[32,2],[32,2],[32,0]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:

                var aux = analizador; 
                analizador = new Object(); 
                 terminal = new Object();
                terminal.lexemas = [];
                 noTerminal = new Object();
                 terminales = [];
                errores = [];
                 nombreNoTerminales = [];
                 prodNoTerminales = [];
                 produccionNoT = new Object();
                produccionNoT.producciones = [];        
                 initialSim = [];
                 //analizador = new Object();        
                analizador.terminales = terminales;
                analizador.noTerminales = nombreNoTerminales;
                analizador.producciones = prodNoTerminales;
                analizador.initialSim = initialSim;
                analizador.errores = errores;
                return aux;
break;
case 2:
 errores.push("Sintactico ||" + $$[$0] + "||  "+ this._$.first_line + "|| " + this._$.first_column + "|| Wison no declarado");
                var aux = analizador; 
                analizador = new Object(); 
                 terminal = new Object();
                terminal.lexemas = [];
                 noTerminal = new Object();
                 terminales = [];
                errores = [];
                 nombreNoTerminales = [];
                 prodNoTerminales = [];
                 produccionNoT = new Object();
                produccionNoT.producciones = [];        
                 initialSim = [];
                 //analizador = new Object();        
                analizador.terminales = terminales;
                analizador.noTerminales = nombreNoTerminales;
                analizador.producciones = prodNoTerminales;
                analizador.initialSim = initialSim;
                analizador.errores = errores;
                return aux;
break;
case 6:
terminal.nombre = $$[$0-4]; terminal.lexemas = terminal.lexemas.concat($$[$0-2]);terminales.unshift(terminal); terminal = new Object(); terminal.lexemas = [];
break;
case 8:
 errores.push("Sintactico ||" + $$[$0-1] + "|| "+ this._$.first_line + "|| " + this._$.first_column + "|| Error en asignacion terminal");
break;
case 9:
 errores.push("Sintactico ||" + $$[$0-5] + "|| "+ this._$.first_line + "|| " + this._$.first_column + "|| No hay nombre de terminal");
break;
case 10: case 11: case 12: case 13:
lexema = new Object(); lexema.nombre = $$[$0-1]; lexema.restr = $$[$0]; this.$ = lexema;
break;
case 14:
arr1 = [$$[$0-2]]; arr2 = [$$[$0]] ; this.$ = arr1.concat(arr2);
break;
case 15:
lexema = new Object(); lexema.nombre = ''; lexema.restr = ''; this.$ = lexema;
break;
case 16:
 errores.push("Sintactico ||" + $$[$0] + "|| "+ this._$.first_line + "|| " + this._$.first_column + "|| Cadena Mal declarada");
break;
case 17: case 18: case 19:
this.$ = $$[$0]
break;
case 20: case 29:
this.$ = ''
break;
case 21:
 errores.push("Sintactico ||" + $$[$0] + "|| "+ this._$.first_line + "|| " + this._$.first_column + "|| Restriccion mal declarada");
break;
case 22:
nombreNoTerminales.unshift($$[$0-2]);
break;
case 23:
initialSim.unshift($$[$0-2]);
break;
case 24:
produccionNoT.nombre = $$[$0-4]; produccionNoT.producciones = $$[$0-2] ;prodNoTerminales.unshift(produccionNoT); produccionNoT = new Object();
break;
case 26: case 27:
this.$ = $$[$0-1] +'+'+$$[$0];
break;
case 28:
this.$ = $$[$0-1] + $$[$0];
break;
}
},
table: [{2:[1,3],3:1,4:[1,2]},{1:[3]},{5:[1,4]},{1:[2,2]},{6:5,7:$V0,8:$V1,13:$V2},{7:[1,8]},{9:[1,9]},{9:[1,10]},{4:[1,11]},{10:[1,12]},{9:[1,13]},{1:[2,1]},{2:$V3,10:$V4,11:14,15:$V5},{10:[1,17]},{10:[1,18]},{2:[1,20],16:[1,19]},{2:$V3,10:$V4,11:21,15:$V5},{10:$V6,14:22,28:$V7,29:$V8,30:$V9},{12:[1,26]},{17:[1,27]},{17:[1,28]},{10:[2,8]},{10:[1,29]},{29:[1,30]},{29:[1,31]},{31:[1,32]},{6:33,7:$V0,8:$V1,13:$V2},{2:$Va,16:$Vb,18:34,19:$Vc,20:$Vd,22:$Ve,23:$Vf,24:$Vg},{2:$Va,16:$Vb,18:41,19:$Vc,20:$Vd,22:$Ve,23:$Vf,24:$Vg},{12:[1,42]},{19:[1,43]},{19:[1,44]},{16:$Vh,19:$Vi,29:$Vj,32:45,33:$Vk},{7:[2,3]},{19:[1,49]},o($Vl,$Vm,{21:50,2:$Vn,7:$Vo,26:$Vp,27:$Vq}),o($Vl,$Vm,{21:55,2:$Vn,7:$Vo,26:$Vp,27:$Vq}),o($Vl,$Vm,{21:56,2:$Vn,7:$Vo,26:$Vp,27:$Vq}),o($Vl,$Vm,{21:57,2:$Vn,7:$Vo,26:$Vp,27:$Vq}),{2:$Va,16:$Vb,18:58,20:$Vd,22:$Ve,23:$Vf,24:$Vg,25:$Vc},o($Vl,[2,16]),{19:[1,59]},{12:[1,60]},{10:$V6,14:61,28:$V7,29:$V8,30:$V9},{10:$V6,14:62,28:$V7,29:$V8,30:$V9},{19:[1,63]},{16:$Vh,19:$Vi,29:$Vj,32:64,33:$Vk},{16:$Vh,19:$Vi,29:$Vj,32:65,33:$Vk},{16:$Vh,19:$Vi,29:$Vj,32:66,33:$Vk},{2:$V3,10:$V4,11:67,15:$V5},o($Vl,[2,10]),o($Vl,[2,17]),o($Vl,[2,18]),o($Vl,[2,19]),o($Vl,[2,21]),o($Vl,[2,11]),o($Vl,[2,12]),o($Vl,[2,13]),{25:[1,68]},{2:$V3,10:$V4,11:69,15:$V5},{6:70,7:$V0,8:$V1,13:$V2},{10:[2,22]},{10:[2,23]},{10:$V6,14:71,28:$V7,29:$V8,30:$V9},{19:[2,26]},{19:[2,27]},{19:[2,28]},{10:[2,6]},o($Vl,$Vc,{18:72,2:$Va,16:$Vb,20:$Vd,22:$Ve,23:$Vf,24:$Vg}),{10:[2,9]},{7:[2,4]},{10:[2,24]},o($Vl,[2,14])],
defaultActions: {3:[2,2],11:[2,1],21:[2,8],33:[2,3],61:[2,22],62:[2,23],64:[2,26],65:[2,27],66:[2,28],67:[2,6],69:[2,9],70:[2,4],71:[2,24]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse (input) {
    var self = this,
        stack = [0],
        tstack = [], // token stack
        vstack = [null], // semantic value stack
        lstack = [], // location stack
        table = this.table,
        yytext = '',
        yylineno = 0,
        yyleng = 0,
        recovering = 0,
        TERROR = 2,
        EOF = 1;

    var args = lstack.slice.call(arguments, 1);

    //this.reductionCount = this.shiftCount = 0;

    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    // copy state
    for (var k in this.yy) {
      if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
        sharedState.yy[k] = this.yy[k];
      }
    }

    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);

    var ranges = lexer.options && lexer.options.ranges;

    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }

    function popStack (n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }

_token_stack:
    var lex = function () {
        var token;
        token = lexer.lex() || EOF;
        // if token isn't its numeric value, convert
        if (typeof token !== 'number') {
            token = self.symbols_[token] || token;
        }
        return token;
    }

    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        // retreive state number from top of stack
        state = stack[stack.length - 1];

        // use default actions if available
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            // read action for current state and first input
            action = table[state] && table[state][symbol];
        }

_handle_error:
        // handle parse error
        if (typeof action === 'undefined' || !action.length || !action[0]) {
            var error_rule_depth;
            var errStr = '';

            // Return the rule stack depth where the nearest error rule can be found.
            // Return FALSE when no error recovery rule was found.
            function locateNearestErrorRecoveryRule(state) {
                var stack_probe = stack.length - 1;
                var depth = 0;

                // try to recover from error
                for(;;) {
                    // check for error recovery rule in this state
                    if ((TERROR.toString()) in table[state]) {
                        return depth;
                    }
                    if (state === 0 || stack_probe < 2) {
                        return false; // No suitable error recovery rule available.
                    }
                    stack_probe -= 2; // popStack(1): [symbol, action]
                    state = stack[stack_probe];
                    ++depth;
                }
            }

            if (!recovering) {
                // first see if there's any chance at hitting an error recovery rule:
                error_rule_depth = locateNearestErrorRecoveryRule(state);

                // Report error
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push("'"+this.terminals_[p]+"'");
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line '+(yylineno+1)+":\n"+lexer.showPosition()+"\nExpecting "+expected.join(', ') + ", got '" + (this.terminals_[symbol] || symbol)+ "'";
                } else {
                    errStr = 'Parse error on line '+(yylineno+1)+": Unexpected " +
                                  (symbol == EOF ? "end of input" :
                                              ("'"+(this.terminals_[symbol] || symbol)+"'"));
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected,
                    recoverable: (error_rule_depth !== false)
                });
            } else if (preErrorSymbol !== EOF) {
                error_rule_depth = locateNearestErrorRecoveryRule(state);
            }

            // just recovered from another error
            if (recovering == 3) {
                if (symbol === EOF || preErrorSymbol === EOF) {
                    throw new Error(errStr || 'Parsing halted while starting to recover from another error.');
                }

                // discard current lookahead and grab another
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                symbol = lex();
            }

            // try to recover from error
            if (error_rule_depth === false) {
                throw new Error(errStr || 'Parsing halted. No suitable error recovery rule available.');
            }
            popStack(error_rule_depth);

            preErrorSymbol = (symbol == TERROR ? null : symbol); // save the lookahead token
            symbol = TERROR;         // insert generic error symbol as new lookahead
            state = stack[stack.length-1];
            action = table[state] && table[state][TERROR];
            recovering = 3; // allow 3 real symbols to be shifted before reporting a new error
        }

        // this shouldn't happen, unless resolve defaults are off
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: '+state+', token: '+symbol);
        }

        switch (action[0]) {
            case 1: // shift
                //this.shiftCount++;

                stack.push(symbol);
                vstack.push(lexer.yytext);
                lstack.push(lexer.yylloc);
                stack.push(action[1]); // push state
                symbol = null;
                if (!preErrorSymbol) { // normal execution/no error
                    yyleng = lexer.yyleng;
                    yytext = lexer.yytext;
                    yylineno = lexer.yylineno;
                    yyloc = lexer.yylloc;
                    if (recovering > 0) {
                        recovering--;
                    }
                } else {
                    // error just occurred, resume old lookahead f/ before error
                    symbol = preErrorSymbol;
                    preErrorSymbol = null;
                }
                break;

            case 2:
                // reduce
                //this.reductionCount++;

                len = this.productions_[action[1]][1];

                // perform semantic action
                yyval.$ = vstack[vstack.length-len]; // default to $$ = $1
                // default location, uses first token for firsts, last for lasts
                yyval._$ = {
                    first_line: lstack[lstack.length-(len||1)].first_line,
                    last_line: lstack[lstack.length-1].last_line,
                    first_column: lstack[lstack.length-(len||1)].first_column,
                    last_column: lstack[lstack.length-1].last_column
                };
                if (ranges) {
                  yyval._$.range = [lstack[lstack.length-(len||1)].range[0], lstack[lstack.length-1].range[1]];
                }
                r = this.performAction.apply(yyval, [yytext, yyleng, yylineno, sharedState.yy, action[1], vstack, lstack].concat(args));

                if (typeof r !== 'undefined') {
                    return r;
                }

                // pop off stack
                if (len) {
                    stack = stack.slice(0,-1*len*2);
                    vstack = vstack.slice(0, -1*len);
                    lstack = lstack.slice(0, -1*len);
                }

                stack.push(this.productions_[action[1]][0]);    // push nonterminal (reduce)
                vstack.push(yyval.$);
                lstack.push(yyval._$);
                // goto new state = table[STATE][NONTERMINAL]
                newState = table[stack[stack.length-2]][stack[stack.length-1]];
                stack.push(newState);
                break;

            case 3:
                // accept
                return true;
        }

    }

    return true;
}};

        /*Codigo JavaScript incustado*/
        var errores = [];
        var restricciones = [];
        var lexemas = [];
        var terminal = new Object();
        terminal.lexemas = [];
        var noTerminal = new Object();
        var terminales = [];

        var nombreNoTerminales = [];
        var prodNoTerminales = [];
        var produccionNoT = new Object();
        produccionNoT.producciones = [];        
        var initialSim = [];
        var analizador = new Object();        
        analizador.terminales = terminales;
        analizador.noTerminales = nombreNoTerminales;
        analizador.producciones = prodNoTerminales;
        analizador.initialSim = initialSim;
        analizador.errores = errores;

/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/*Blancos*/
break;
case 1:return 4;
break;
case 2:return 15;
break;
case 3:return 28;
break;
case 4:return 13;
break;
case 5:return 8;
break;
case 6:return 30;
break;
case 7:return 5;
break;
case 8:return 7;
break;
case 9:return 9;
break;
case 10:return 12;
break;
case 11:return 10;
break;
case 12:return 19;
break;
case 13:return 26;
break;
case 14:return 27;
break;
case 15:return 24;
break;
case 16:return 25;
break;
case 17:return 17;
break;
case 18:return 31;
break;
case 19:return 33;
break;
case 20:return 16;
break;
case 21:return 29;
break;
case 22:return 22;
break;
case 23:return 23;
break;
case 24:return 20;
break;
case 25:/*Comentario 1*/
break;
case 26:/*Comentario 2*/
break;
case 27:return 'EOF';
break;
case 28: errores.push("Lexico ||" + yy_.yytext + "|| "+ yy_.yylloc.first_line + "|| " + yy_.yylloc.first_column + "|| Lexema no detectado");/*console.error("errore lexico");*/
break;
}
},
rules: [/^(?:[ \r\t\b\f\n]+)/,/^(?:Wison\b)/,/^(?:Terminal\b)/,/^(?:No_Terminal\b)/,/^(?:Syntax\b)/,/^(?:Lex\b)/,/^(?:Initial_Sim\b)/,/^(?:¿)/,/^(?:\?)/,/^(?:\{)/,/^(?:\})/,/^(?::)/,/^(?:;)/,/^(?:\*)/,/^(?:\+)/,/^(?:\()/,/^(?:\))/,/^(?:<-)/,/^(?:<=)/,/^(?:\|)/,/^(?:\$_[a-zA-Z0-9_]+)/,/^(?:%_[a-zA-Z0-9_]+)/,/^(?:\[aA-zZ\])/,/^(?:\[0-9\])/,/^(?:‘([a-zA-Z0-9\[\]{}+\-*\/:;¿?\%()#]|[!@$>\^,.])+’)/,/^(?:#([a-zA-Z0-9\[\]{}+\-*\/:;¿?\%()#_<>=]|[!@$>\^,.]|[ ])+)/,/^(?:\/\*\*([a-zA-Z0-9\[\]{}+\-*\/:;¿?\%()#_<>=]|[!@$>\^,.]|[ \r\n])*\*\/)/,/^(?:$)/,/^(?:.)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = gramatica;
exports.Parser = gramatica.Parser;
exports.parse = function () { return gramatica.parse.apply(gramatica, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}